[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
test = "test"
script = "script"
cache_path = "cache_forge"
solc_version = "0.8.29"
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
via_ir = true
gas_reports = ["*"]

[profile.ci]
fuzz = { runs = 100 }
invariant = { runs = 10 }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
bnb = "${BNB_MAINNET_RPC_URL}"
base = "${BASE_MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"


